config/routes.rb
Rails.application.routes.draw do
  get 'genres/index'
  
  resources :genres
  
  root 'genres#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    def index
    	@genres = Genre.all
    end

    def show
    	@genre = Genre.find(params[:id])
    end

    def new
    	@genre = Genre.new
    end
    
    def create
    	@genre = Genre.new(genre_params)
    	if @genre.save
    		redirect_to action: "index"
    	else
    		redirect_to :back
    	end
    end

    private
    	def genre_params
    		params.require(:genre).permit(:name,:file)
    	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/genres/index.html.erb
<div id = "existing">
  <div id = "question">
      <h3>what genre of art do you make?</h3>
  </div>
  <div class = "photos">
  	<% @genres.each do |genre| %>
	    <div class = "genre">
	    	<div class = "picture">
	    		<%= image_tag(genre.file, alt: "") %>
	    	</div>
	    	<div class = "name">
  				<h4><%= genre.name%></h4>
  			</div>
	    </div>
  	<% end %>
  </div>
</div>
<div id = "new">
	<%= link_to 'Create a new genre', new_genre_path %>
</div>
<div id = "selection">
      <a href="#" id = "choose"><h3>choose</h3></a>
 </div>

app/views/genres/new.html.erb
<h1>Add a New Genre</h1>


 <%= form_for Genre.new do |form|%>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.file_field :file, accept: 'image/png,image/jpeg,image/jpg'%>
  </p>
  <p>
    <%= form.submit %>
  </p>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Artisans' Guild</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">the Artisans' Guild</a>
          </div>
        </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div id = "existing">
  <div id = "question">
      <h3>what genre of art do you make?</h3>
  </div>
  <div id = "photos">
  </div>
  <div id = "selection">
      <h3>choose</h3>
  </div>
</div>
<div id = "new photos">
</div>